### ISSUE TITLE
Bug: spacing in blog posts

### ISSUE THREAD

**Issue by fmerian** [open-sauced/landing-page#107]
### Describe the bug

More spacing between paragraphs (and also, headlines) would improve readability imho.

- [Retaining the best engineers](https://opensauced.pizza/blog/retaining-the-best-engineers)
- [Measuring success in open source](https://opensauced.pizza/blog/measuring-success-in-open-source)

![open-sauced-landing-page-blog](https://user-images.githubusercontent.com/1890087/220563030-1f656215-4718-4bb3-bacf-69ca99d0240c.png)

### Steps to reproduce

1. Go to `https://opensauced.pizza/blog/`
2. Click on `/measuring-success-in-open-source`

### Affected services

opensauced.pizza

### Platforms

Desktop, Mobile, Tablet

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Thanks for calling this out. We fixed it in the one blog post and I need to go in and fix the others now.

**Comment by fmerian** [comment]
how about making posts available here on GitHub? would be happy to fix them.

related: would you be open to guest posts?
