### ISSUE TITLE
Feature: Redirect opensauced.pizza/username to /user/username

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#124]
### Type of feature

🍕 Feature

### Current behavior

Working on social cards and it would be nice to redirect these urls. 

![Group 1 (5)](https://github.com/open-sauced/insights/assets/5713670/7d1a6578-7028-4fa6-8ed6-9ccd345b404e)

### Suggested solution

Add a redirect in Netlify

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
@bdougie Did you mean https://opensauced.pizza/username to https://insights.opensauced.pizza/user/username?

**Comment by bdougie** [comment]
> @bdougie Did you mean https://opensauced.pizza/username to https://insights.opensauced.pizza/user/username?

Yes. This will most likely need an edge function to quickly check if the user exist in the API.

Open to other suggestions.

**Comment by shamimbinnur** [comment]
> > @bdougie Did you mean https://opensauced.pizza/username to https://insights.opensauced.pizza/user/username?
> 
> Yes. This will most likely need an edge function to quickly check if the user exist in the API.
> 
> Open to other suggestions.

@bdougie Where would the user be redirected if the user doesn't exist?

Since we are redirecting users to the insight, shouldn't the insight app handle the rest?

**Comment by bdougie** [comment]
> Since we are redirecting users to the insight, shouldn't the insight app handle the rest?

Correct ideally the insights app would have a 404. Today the page displays with errored data if not found.

**Comment by bdougie** [comment]
Might be better suited for a URL shortener.

**Comment by shamimbinnur** [comment]
@bdougie If we use the "/username" path we will be required to check our existing pages ('/blog', '/teams) and add some logic to treat these as reserved paths. And this has to be refactored every time we add a new route for pages.

But if we use "/u/username" we will not be required the checking.

Which path should we go for?

**Comment by bdougie** [comment]
Let's go with /u

**Comment by shamimbinnur** [comment]
@bdougie This issue has been fixed and addressed in #128
