### ISSUE TITLE
Feature: Move the border behind the sauce

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#13]
### Type of feature

🍕 Feature

### Current behavior

<img width="1728" alt="Screen Shot 2022-05-13 at 12 54 25 PM (2)" src="https://user-images.githubusercontent.com/5713670/168475440-a50e2974-9d48-41aa-b3fd-7316387bf15d.png">

### Suggested solution

Move the border behind using z-index?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
@bdougie Screenshot is not visible.

**Comment by bdougie** [comment]
updated @shamimbinnur

**Comment by shamimbinnur** [comment]
@bdougie  Alternative solution has been implemented on commit c4521d7932a89438ce2fb9dc14797f91775be7ba
