### ISSUE TITLE
Bug: blog post doesn't show up on landing page

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/landing-page#132]
### Describe the bug

The Intro to Open Source blog post is on the site, but is only viewable if you have the url. 

### Steps to reproduce

- got to https://opensauced.pizza/blog/
- notice it's not there. 

Here's the live url: https://opensauced.pizza/blog/open-source-101:-a-beginner's-guide-to-getting-started

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment]
@bdougie I can't assign you, so wanted to tag you here.

**Comment by bdougie** [comment]
confirmed it shows on local dev. Curious if you have thoughts on why that is @shamimbinnur 

<img width="1608" alt="Screen Shot 2023-07-10 at 11 09 04 PM" src="https://github.com/open-sauced/landing-page/assets/5713670/e3027b49-9b09-4a9f-9300-7688024b8ce1">

**Comment by shamimbinnur** [comment]
@bdougie Initially, all blogs were fetched unsorted from the backend, resulting in potential blog omissions when sorting was done on the frontend. This sorting operation shouldn't be performed on the frontend. Refactored the code on #134 to fetch sorted data directly from the backend. Hopefully [this](https://github.com/open-sauced/landing-page/pull/134) PR will fix this issue.

**Comment by bdougie** [comment]
> @bdougie Initially, all blogs were fetched unsorted from the backend, resulting in potential blog omissions when sorting was done on the frontend. This sorting operation shouldn't be performed on the frontend. Refactored the code on #134 to fetch sorted data directly from the backend. Hopefully [this PR](https://github.com/open-sauced/landing-page/pull/134) will fix this issue.

This helpful context and the correct approach. Featured posts are no longer needed to be fetched as well. 

Appreciate the PR. Let's move forward with that.
