### ISSUE TITLE
Bug: no padding top in social icons on nav menu 

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/landing-page#138]
### Describe the bug

There is no padding top on social icons in the nav menu on the landing page 
![Screenshot_20230723-215406](https://github.com/open-sauced/landing-page/assets/72051159/ffa26e7c-4418-40a8-9cbe-6cca3051bcb0)

### Steps to reproduce

1. Go to opensauced.pizza
2. Click on the nav button
3. See the issue 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
Hum, I saw it on small screens. Feel free to take it

**Comment by dev-phantom** [comment]
.take

**Comment by dev-phantom** [comment]
this issue has been fixed in #144 
i am closing this issue now
