### ISSUE TITLE
Bug: text overflow on footer

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/landing-page#139]
### Describe the bug

There is a text overflow in the link "insight.opensauced.pizza" on mobile view footer section 
![Screenshot_20230723-215451](https://github.com/open-sauced/landing-page/assets/72051159/190502cc-9cdc-495c-9747-1a5052ed73a6)

### Steps to reproduce

1. Go to opensauced.pizza
2. Scroll down to footer
3. See error

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
Tried different mobile screen sizes (using devtools) but couldn't reproduce it. Which size did you see it?

**Comment by dev-phantom** [comment]
> Tried different mobile screen sizes (using devtools) but couldn't reproduce it. Which size did you see it?

![Screenshot_20230724-215100](https://github.com/open-sauced/landing-page/assets/72051159/e46556c6-6cc9-4a5f-ba48-fda9c3617c9b)
Here is my mobile screen size

**Comment by wasimapinjari** [comment]
That's not how you reproduce the problem. His phone screen is smaller than the dev tools simulation @takanome-dev. 

You can see the problem by docking the developer tools on the side and dragging it all the way to the opposite side to simulate the smaller phone screens. 

You will see the overflowing text that's what he is talking about.

![Screenshot (196)](https://github.com/open-sauced/landing-page/assets/95426296/bbddf612-a2ec-45e5-9ce0-56a819726f01)

**Comment by wasimapinjari** [comment]
You can fix that like so:

![Screenshot (201)](https://github.com/open-sauced/landing-page/assets/95426296/e49e6350-668a-4a9a-8443-5fbb2f3a2c8d)

**Comment by dev-phantom** [comment]
.take

**Comment by dev-phantom** [comment]
@takanome-dev @jpmcb  is it possible i get assigned to the project on sanity 
cause i get this error anytime i try to run this locally 
Image with src "https://cdn.sanity.io/images/r7m53vrk/production/2b1682c6670e30015f598d181b8343c63da3ec83-1024x1024.png" has legacy prop "objectFit". Did you forget to run the codemod?

**Comment by bdougie** [comment]
Removing padding in the left column would be more ideal than wrapping on this.
