### ISSUE TITLE
Feature: Feature screen updates

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#14]
### Type of feature

🍕 Feature

### Current behavior

![Screen Shot 2022-05-13 at 3 29 32 PM](https://user-images.githubusercontent.com/5713670/168397121-20176da6-9a1b-4d66-9dbd-bb4080d17764.png)

### Suggested solution

- [ ] implement nav from home page
- [ ] move cta button, description and title 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
Feature screen has been updated on commit 0781beaa633c527352aa223874e70280d3fc22c7
