### ISSUE TITLE
Bug: overflow x on the insight page

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/landing-page#141]
### Describe the bug

There is an overflow x on the insight page after authentication 

https://github.com/open-sauced/landing-page/assets/72051159/cb78b3af-e53b-4248-82a3-55dbfdd8ead9

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/hub/insights
2. Swipe left and right
3. See error 

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
@dev-phantom can you move this to the insights repo?
