### ISSUE TITLE
Styles: size of icons and scoll bar

### ISSUE THREAD

**Issue by euotiniel** [open-sauced/landing-page#143]
## Icons 

I think the minimalist pattern on the icons could also be kept. That is, reduce the size.

Like, we have this

![1](https://github.com/open-sauced/landing-page/assets/93485038/4cc30c90-8cd3-4acd-80e5-1b6207572f21)

But we could in the blink of an eye, switch to that 

![2](https://github.com/open-sauced/landing-page/assets/93485038/2c362684-a990-4772-982f-0f6d02c286ff)

## Scroll bar 

Stylize the scoll bar, put a color on the background and change the look of it, give an air more to "pizza" kkk. I'm talking about the beautiful black combined with the orange.
> No image modifications.

![3](https://github.com/open-sauced/landing-page/assets/93485038/e0b5fa1a-dca8-4c0a-92a4-508fd5fe3b55)

## Extra

Maybe they should add more information in the contacts, in addition to the email, a phone number, an address or the like.

**Comment by preshpi** [comment]
@euotiniel I really want to do this but setting the project on my system isn't working even after I followed the information in the readme and installed all it said but whenever i try to run, it throws an error. I don't if you can help, thanks.

**Comment by euotiniel** [comment]
@preshpi What exactly is the error? Can you send prints?

**Comment by preshpi** [comment]
@euotiniel The issue was the node_modules so I had to delete it before and install it back so it works. Can I work on it now?

**Comment by preshpi** [comment]
Okay thanks @bdougie
