### ISSUE TITLE
Bug: overflowing text and no room for text

### ISSUE THREAD

**Issue by wasimapinjari** [open-sauced/landing-page#147]
### Describe the bug

The card content is overflowing the card.

The paragraph needs some bottom padding.

The issue can be fixed by changing media query points (I guess) and adding padding-bottom to the paragraph

![Screenshot (204)](https://github.com/open-sauced/landing-page/assets/95426296/cfd8354e-b442-4a41-8560-cc5554a98944)

### Steps to reproduce

1. Open the browser's developer tools (preferably use Chrome), dock it to one side, and drag it to the opposite side until you see the problem area just like I did in the provided screenshot image.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
If this grid is set to display two items per row on this screen size i feel it should solve this isssue

**Comment by bdougie** [comment]
Seems like a good approach

**Comment by dev-phantom** [comment]
.take
