### ISSUE TITLE
Bug: active link indicator doesn't work on feature (home) page

### ISSUE THREAD

**Issue by wasimapinjari** [open-sauced/landing-page#149]
### Describe the bug

This may be an intentional design choice.

But clicking on the "Features" link doesn't show the orange border bottom indicating to the user that they are currently viewing the "Features" page.

https://github.com/open-sauced/landing-page/assets/95426296/3e38d67b-ce36-456f-b483-88115b8b8f02

### Steps to reproduce

1. Click on the "Features" link

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
> We do not need the features underlined when the page is visited without the routes. If it is possible only to add the underline when the URL includes the `features` route, I would say let's do it.
> 
> This is not a high priority fix

i guess adding an activeClass to the tab that is currently active should fix this

**Comment by dev-phantom** [comment]
> > We do not need the features underlined when the page is visited without the routes. If it is possible only to add the underline when the URL includes the `features` route, I would say let's do it.
> > This is not a high priority fix
> 
> i guess adding an activeClass to the tab that is currently active should fix this

@bdougie what is your take on this?

**Comment by bdougie** [comment]
I don't have a take

**Comment by wasimapinjari** [comment]
Fun hover effect 😃 

https://github.com/open-sauced/landing-page/assets/95426296/577bf98a-8b7c-4bda-af2e-b321d6706925

**Comment by dev-phantom** [comment]
I don't think there a need for this issue 
can you kindly close this
