### ISSUE TITLE
Feature: Swap video out for a youtube

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#15]
### Type of feature

🍕 Feature

### Current behavior

The video on the feature page is uploaded in Sanity. Ca need to switch it to a YouTube video. 

### Suggested solution

Let's swap it with this, https://www.youtube.com/watch?v=ms_tI6KAws0

We will want to make it a YouTube embed. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
Resolved on commit 843d6c9afa41a393b338ce6336b9647f7ec42df5
@bdougie  You need to merge the branch imedietely!
