### ISSUE TITLE
Bug: overflowing card animation + solution

### ISSUE THREAD

**Issue by wasimapinjari** [open-sauced/landing-page#156]
### Describe the bug

Animation is overflowing. It's pretty self-explanatory.

The top and bottom of the card get cut in-between animations. 

Also, the top and bottom of the orange box shadow get cut when the animation is complete.

https://github.com/open-sauced/landing-page/assets/95426296/ccb69ba0-bcd8-4c8b-abb0-b8b7f5a4535a

### Steps to reproduce

1. Scroll the card section on a small screen device like a phone or something. Alternatively, open a browser's developer tools (preferably use Chrome), dock it to one side, and drag it to the opposite side until you see the problem area just like I did in the provided video.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
i guess one way to fix this is a adding animation-delay to the cards

**Comment by bdougie** [comment]
IMO removing the ease in and appear animation. At the point the user scrolls this far down the page, they don't need to see the animation, we can just show the cards.

**Comment by dev-phantom** [comment]
.take

**Comment by wasimapinjari** [comment]
Few considerations + problems:

1. Animation sucks the performance out of the website and it should be removed whenever possible, removing the animation from cards is a wise choice. 

2. I think the whole website animation can be improved by lowering the delay even more. This website seems to be inspired by the GitHub landing page but they have a low delay time if you take a closer look and it's often for a reason because people don't like to wait for the animation to finish. I like animation but only when it's not getting in the way of user experience.

3. We still need to add a little top & bottom margin because the container div is blocking the top and bottom box shadow. It has nothing to do with animation. @dev-phantom fixed that with padding which is a nice solution as well.

![IMG_20230807_233114.jpg](https://github.com/open-sauced/landing-page/assets/95426296/afd8be6e-7f8b-4e41-a971-9f1fd38d91ca)


4. I also noticed other problems:  if you take a look at text content and profile image they are too close when viewed on small screen devices. There is only one card that seems to have this problem and there is a need for a bottom margin or padding to fix the problem.

5. There is also a mistake in writing the Twitter user title name at the bottom instead of up and writing the Twitter handle at the top instead of the bottom, they both need to switch places. Some cards got this correct whereas others don't. This is most likely going to require a change in the saved content data itself.

That's it for now. I got more issues for later. 😃

**Comment by wasimapinjari** [comment]
@dev-phantom I am currently learning React and most likely will not fix any of those issues. 

Feel free to open an issue if you're planning to fix any or all of them. 😀

**Comment by dev-phantom** [comment]
> @dev-phantom I am currently learning React and most likely will not fix any of those issues. 
> 
> Feel free to open an issue if you're planning to fix any or all of them. 😀

You can still open those issue, other developers would work on it

You can also try taking on one of the issue also it'll be a great way to learn react and typescript
