### ISSUE TITLE
Bug: no close button

### ISSUE THREAD

**Issue by wasimapinjari** [open-sauced/landing-page#161]
### Describe the bug

There is no close button. 

https://github.com/open-sauced/landing-page/assets/95426296/a69812f7-7705-4abc-81ac-e36d85752ad6

You don't need fancy animation like the example ones, just switching between close and hamburger icons is good enough as well. 

It's good for accessibility as well.

Reference help: [codepen.io/jonraedeke/pen/WRwJQX](https://codepen.io/jonraedeke/pen/WRwJQX)

SVG for the close button (source: [heroicons.com](https://heroicons.com)):

``` HTML
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
</svg>
```

### Steps to reproduce

1. Click on the hamburger icon for opening the menu on small-screen devices

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
I guess that design was intensional and also this should be a feature request not a bug

**Comment by wasimapinjari** [comment]
I was initially going to make it a feature request but then I thought it really feels like a bug to me there is no close button because I rarely come across such website that don't implement it 😅

**Comment by dev-phantom** [comment]
@bdougie should I add a toggle close button or that is how the design is meant to be?

**Comment by CBID2** [comment]
Hmmm, if we replace the hamburger menu with a close button, where should we put the other tabs @wasimapinjari? 🤔

**Comment by dev-phantom** [comment]
> Hmmm, if we replace the hamburger menu with a close button, where should we put the other tabs @wasimapinjari? 🤔

🤔
Sorry please what other tabs?
I guess what he trying to say is we'll retain the hamburger button but there will be a toggle close button like the example he showed in the video

So when you click on the hamburger it'll show the close hamburger button

**Comment by bdougie** [comment]
@dev-phantom your solution sounds ideal

**Comment by CBID2** [comment]
> > Hmmm, if we replace the hamburger menu with a close button, where should we put the other tabs @wasimapinjari? 🤔
> 
> 🤔 Sorry please what other tabs? I guess what he trying to say is we'll retain the hamburger button but there will be a toggle close button like the example he showed in the video
> 
> So when you click on the hamburger it'll show the close hamburger button

Ohh I get what you mean now @dev-phantom. Hey @wasimapinjari, I rewatched your clip, and I agree with @bdougie. It'll be a great idea.

**Comment by dev-phantom** [comment]
.take
