### ISSUE TITLE
Feature: Resize for mobile (features)

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#17]
### Type of feature

🍕 Feature

### Current behavior

<img width="359" alt="Screen Shot 2022-05-15 at 7 40 03 AM" src="https://user-images.githubusercontent.com/5713670/168478575-12468e47-0bd9-49a1-95d8-a599617984a5.png">

On mobile the icons are huge. Can we bump these to 25% height.

### Suggested solution

1. 25% height
2. Move icon and title to the same line.

<img width="1165" alt="Screen Shot 2022-05-15 at 7 43 15 AM" src="https://user-images.githubusercontent.com/5713670/168478687-93725e41-068b-4b1c-bcc2-802fca607adc.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
This issue has been resolved on commit 8b9f21dbf00031b5839b00d160dc84ad9a60805b
