### ISSUE TITLE
Bug: Unable to run sanity install because sanity/tsconfig.json throw an error.

### ISSUE THREAD

**Issue by Sunny-unik** [open-sauced/landing-page#170]
### Describe the bug

I cloned the project and ran the process from scratch but sanity/tsconfig.json throws an error and sanity start unable to execute, that is because commit id 8364b76 tsconfig.json inside sanity directory is updated in incorrect format.

### Steps to reproduce

1. clone repo 
2. start the installation (using README.md)
3. run development sanity server

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
@Sunny-unik, thanks for bringing this to our attention. Mind adding the error you get to the issue? Thanks!

**Comment by Sunny-unik** [comment]
Error: /home/sunny/Work/Projects/repos/others/landing-page/sanity/tsconfig.json is malformed JSON5: invalid character '}' at 24:1

I'm getting this error on running `sanity start`

**Comment by bdougie** [comment]
> Error: /home/sunny/Work/Projects/repos/others/landing-page/sanity/tsconfig.json is malformed JSON5: invalid character '}' at 24:1
> 
> I'm getting this error on running `sanity start`

I run it locally and do not get any error messages. I don't see how all the extra options were added, but I'm curious if someone else on @open-sauced/engineering could close this repo and run `sanity start` to see if that has an issue. 

I did see sanity V3 had changes that I accepted and that would be the reason why I did not see an error.

**Comment by takanome-dev** [comment]
Yeah, I'm getting the same error. It was introduce [here](https://github.com/open-sauced/landing-page/pull/102/files#diff-6f4e7922b5bdc22e3361470e13c2feeedf25512c885ae649e657525910d05243)
