### ISSUE TITLE
Feature: Add Gitpod and Codespaces to README File 

### ISSUE THREAD

**Issue by CBID2** [open-sauced/landing-page#174]
### Type of feature

🍕 Feature

### Current behavior

In my experience working with open source beginners, sometimes the directions to setting up a code environment do not always pan out, which creates a frustrating experience. Furthermore, some might not be able to afford their own computer and can only use virtual IDEs.

### Suggested solution

Adding links to [CodeSpaces](https://github.com/features/codespaces) and [Gitpod](https://www.gitpod.io/) to the Readme can make it easier for open source beginners to get started. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by Lymah123** [comment]
@CBID2 , can I work on the issue?

**Comment by CBID2** [comment]
> @CBID2 , can I work on the issue?

Sure @Lymah123

**Comment by bdougie** [comment]
This is probably better suited in the .github repo's contributing.md. Adding in every readme is not ideal. 

I'd also recommend trying to run the project in a codespace to see if it is even possible. I have my doubts the cms works without configuration.

**Comment by Lymah123** [comment]
> This is probably better suited in the .github repo's contributing.md. Adding in every readme is not ideal.
> 
> I'd also recommend trying to run the project in a codespace to see if it is even possible. I have my doubts the cms works without configuration.

Okay, I will try running it in a codespace. 
Thank you, @bdougie!

**Comment by CBID2** [comment]
Moving this to the .github folder per Brian's suggestion.
