### ISSUE TITLE
Bug: Font and stylesheet should be add _document.

### ISSUE THREAD

**Issue by Sunny-unik** [open-sauced/landing-page#177]
### Describe the bug

Getting warning in development on browser's console "Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700&family=Open+Sans:wght@300;400;500;600;700;800&display=swap"). Use Document instead." 
This link tag is used in SEO component.

### Steps to reproduce

1. Run `npm run dev`
2. Open the home page in a browser
3. Check warnings in console

### Additional context (Is this in dev or production?)

Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
Hey @Sunny-unik, this is a quick fix. If you would like to take it, feel free to do that.
Here is a link to the context https://nextjs.org/docs/messages/no-stylesheets-in-head-component

**Comment by Sunny-unik** [comment]
Sure, this is a quick fix but should I remove the linkhref props from the SEO component because it is not in use

**Comment by shamimbinnur** [comment]
Hey @Sunny-unik 

The SEO component is being reused throughout the whole site. And the `linkref` props is required. Don't remove this.
Just take away the value `"https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700&family=Open+Sans:wght@300;400;500;600;700;800&display=swap"}` from there and place it into this [component](https://github.com/open-sauced/landing-page/blob/main/pages/_document.tsx).

This should resolve the issue :)

**Comment by Sunny-unik** [comment]
Fine, you can assign this to me.

**Comment by Sunny-unik** [comment]
> Hey @Sunny-unik
> 
> The SEO component is being reused throughout the whole site. And the `linkref` props is required. Don't remove this. Just take away the value `"https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700&family=Open+Sans:wght@300;400;500;600;700;800&display=swap"` from there and place it into this [component](https://github.com/open-sauced/landing-page/blob/main/pages/_document.tsx).
> 
> This should resolve the issue :)

Remove only font link should not resolve this issue we also need to remove rel='stylesheet'

**Comment by shamimbinnur** [comment]
Yep! You can't leave it empty. `rel` needs to be removed too.

**Comment by nickytonline** [comment]
For including the Inter font in a way that Next.js doesn't give warnings, you can do the same thing we did in the app repo. https://github.com/open-sauced/app/issues/2071
