### ISSUE TITLE
Feature: upgrade to Sanity v3

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#185]
### Type of feature

🍕 Feature

### Current behavior

Sanity V3 was announced - https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization?mkt_tok=MzA4LVVUSC03NDAAAAGO58Jp1E_gu0KKC21ZFV8tQ7sM1khSePRon69625TSbiJT1WylRxXSYTN5gmoVl9IJBoKRgLUTw4UfJP4yJv9TyS-N5ft7qNnVtQ7mciMK

Sanity V2 will deprecate December 7th

### Suggested solution

1. Migrate to V3. 
2. Check for regressions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
.take
