### ISSUE TITLE
Bug: make changelog subtext accessible

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/landing-page#198]
### Describe the bug

On the changelog pages, it appears that the text next to bullet points is inaccessible. We need to make this a lighter color.

<img width="614" alt="image" src="https://github.com/open-sauced/landing-page/assets/34313413/901856f5-814c-4e24-9fa2-0446765d71c4">

### Steps to reproduce

Go to: https://opensauced.pizza/changelog/add-explainer-tootlip-to-cards-on-list-pages

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
.take

**Comment by nickytonline** [comment]
To fix this add the CSS class `prose-ul:text-textPrimary` to this <ReactMarkdown />` component.

https://github.com/open-sauced/landing-page/blob/4285327a6b564853cd859d11be1423a04a8c2b6b/pages/changelog/%5Bslug%5D.tsx#L53-L56

I'm not sure how all the typography is set up in this project as the base color appears to be really dark for a dark background, but that can be for another day.

**Comment by dev-phantom** [comment]
> To fix this, add the CSS class `prose-ul:text-textPrimary` to this `<ReactMarkdown />` component.
> 
> https://github.com/open-sauced/landing-page/blob/4285327a6b564853cd859d11be1423a04a8c2b6b/pages/changelog/%5Bslug%5D.tsx#L53-L56
> 
> I'm not sure how all the typography is set up in this project as the base color appears to be really dark for a dark background, but that can be for another day.

thanks for this!

creating a PR on this now 
.take
