### ISSUE TITLE
Feature page description & landing

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#20]
> Thanks for putting #19  up @shamimbinnur.
> 
> Only two things and I think this is done.
> 
> 1. Can we add a similar transparent border to the feature copy on the page
> 2. Can we add the Footer to the feature pages.
> 
> ## Adding a transparent background will make this more ledge-able.
> ![Screen Shot 2022-05-16 at 10 50 19 AM](https://user-images.githubusercontent.com/5713670/168653264-1bcb0dc9-8d73-4f57-b44c-b747da07a6cc.png)
> 
> This was a great solution ![Screen Shot 2022-05-16 at 10 53 25 AM](https://user-images.githubusercontent.com/5713670/168653441-e0d82d95-a9fa-4f49-9a3d-62c44788f80e.png)

@bdougie can you open an issue for this?

_Originally posted by @shamimbinnur in https://github.com/open-sauced/landing-page/issues/19#issuecomment-1127996191_

**Comment by shamimbinnur** [comment]
Resolved on aa08ba119df5f0400427c37e8c2e75d6c2dcbe81

**Comment by bdougie** [comment]
One more thing. The footer is needed on the feature page as well.

<img width="351" alt="Screen Shot 2022-05-17 at 3 43 56 AM" src="https://user-images.githubusercontent.com/5713670/168793750-338c593c-6a67-4d61-98c7-adf1512bc93a.png">

**Comment by shamimbinnur** [comment]
Footer added on ec090c0db4fdaa85834759b848bb7b9801896ed9
