### ISSUE TITLE
Feature: Create companies page

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/landing-page#205]
### Type of feature

🍕 Feature

### Current behavior

N/A

### Suggested solution

Build the landing page for companies, using the copy provided in the mockup. Images WIP, use placeholders in the meantime :)

**[Figma](https://www.figma.com/file/a2Ay1zhFAIDPmiEbTYVOID/OpenSauced-Brand?type=design&node-id=2714-4663&mode=design&t=N9GyFfpTP1fC9Z1V-4)**

![image](https://github.com/open-sauced/landing-page/assets/27322879/082786fe-9914-4a36-b39b-ecf00ed3d4c4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by isabensusan** [comment]
changing the url / naming to /teams

**Comment by zeucapua** [comment]
Where should the `Contact Sales` buttons redirect to?
