### ISSUE TITLE
Feature: Add `Use Cases` dropdown in navigation bar

### ISSUE THREAD

**Issue by zeucapua** [open-sauced/landing-page#207]
### Type of feature

🍕 Feature

### Current behavior

N/A

### Suggested solution

Implement a dropdown menu that leads to various marketing pages
- [ ] For teams: `/teams`
- [ ] Startups: `/startups`
- [ ] Students: `/students`
- [ ] Contributors: `/contributors`
- [ ] Maintainers: `/maintainers`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by isabensusan** [comment]
for reference -- we could use this component:

https://ui.shadcn.com/docs/components/navigation-menu

<img width="719" alt="image" src="https://github.com/open-sauced/landing-page/assets/27322879/ac27543c-339f-4a2a-b74b-af4e8e12172c">



We'd only need 3 links and the titles/subtitles for each would be:

**Teams** (/teams)
Insights to validate and share the impact of open source to your organization.


**Maintainers** (/maintainers)
Grow and celebrate your open source community.


**Contributors** (/contributors)
Start the path to your next contribution.

**Comment by zeucapua** [comment]
What should the `Features` tab go to? With #209, it will redirect to `/#features` which wouldn't exist, since it's been moved to `/contributors`.

**Comment by isabensusan** [comment]
we can just kill the features link
