### ISSUE TITLE
Fix: small UI fixes

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#23]
### Type of feature

🐛 Fix

### Current behavior

The designer took a look at a few things and identify a few areas where the design did not line up. 

### Suggested solution

Below is a PDF with their notes

### Additional context

[OpenSauced_WebsiteNotesSinglePage_052022.pdf](https://github.com/open-sauced/landing-page/files/8755069/OpenSauced_WebsiteNotesSinglePage_052022.pdf)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
Hey @bdougie can I give it a shot ??

**Comment by bdougie** [comment]
This is already being worked on.

**Comment by shamimbinnur** [comment]
@bdougie 
Issues has been fixed on commit 824bfce859836797fb06f5bfed0cbb5bc080a04c
