### ISSUE TITLE
Feature: Add date to Blog Posts 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#237]
### Type of feature

🍕 Feature

### Current behavior

As an effort to improve SEO, we need to add a date on our blog post. 

<img width="1406" alt="Screen Shot 2024-04-09 at 12 53 42 PM" src="https://github.com/open-sauced/landing-page/assets/5713670/49504950-e05f-46b5-8ac2-bf49684d2866">

### Suggested solution

My thought is to mirror exaclty what we have for changelog. Though I am open to suggestions. 

<img width="870" alt="Screen Shot 2024-04-09 at 12 54 10 PM" src="https://github.com/open-sauced/landing-page/assets/5713670/e02e9656-2724-46d0-b2ac-32e813d5e7b5">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by isabensusan** [comment]
Adding a small request to make the date format more human, the same way we do in the changelog component.

<img width="297" alt="image" src="https://github.com/open-sauced/landing-page/assets/27322879/84c2c002-3bd5-405d-9d5c-dbecddb1e623">

**Comment by isabensusan** [comment]
make date 2xl and human format

<img width="839" alt="image" src="https://github.com/open-sauced/landing-page/assets/27322879/6345ee38-a2a1-4ef0-a2f8-e71a1f5b00f7">

**Comment by isabensusan** [comment]
calendar icon incoming

<img width="921" alt="image" src="https://github.com/open-sauced/landing-page/assets/27322879/ad5b3a29-b374-4393-b711-97999454b82c">

**Comment by nickytonline** [comment]
If we add dates, ensure to use an [HTML time element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time). It can help SEO and also makes the page more accessible.
