### ISSUE TITLE
Feature: Add author bios to blog posts

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#238]
### Type of feature

🍕 Feature

### Current behavior

As an effort to improve SEO, adding author bios aligns with Google's anti-AI content rules. 

### Suggested solution

My though is the easiest is adding a bio for all existing authors. Make the author input only be chosen from a list of authors we have bios for. 

example from ars technica includes bios under the post. 

https://arstechnica.com/gadgets/2024/04/waymo-and-uber-eats-team-up-for-automated-food-deliveries/

<img width="857" alt="Screen Shot 2024-04-09 at 12 58 04 PM" src="https://github.com/open-sauced/landing-page/assets/5713670/4081e16b-b315-4ebe-9b09-aac9627051c5">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by isabensusan** [comment]
quick mock

<img width="482" alt="image" src="https://github.com/open-sauced/landing-page/assets/27322879/aea78069-ac64-447c-925d-f6121a4d9c99">

![image](https://github.com/open-sauced/landing-page/assets/27322879/a2b9635b-e902-4988-84be-b1bb179b77a2)
