### ISSUE TITLE
Links are not visible on changelog. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#256]
This was brought up when sharing today's tweet. The CTA is not visible. FYI @isabensusan, I can fix this now. 

![Screenshot 2024-04-30 at 9 22 17 PM](https://github.com/open-sauced/landing-page/assets/5713670/e4446590-0b46-4fd3-9f6b-2707c595a2d8)

**Comment by nickytonline** [comment]
It's related to this PR not being merged yet. https://github.com/open-sauced/landing-page/pull/254
