### ISSUE TITLE
 On mobile view, the feature title looks huge.

### ISSUE THREAD

**Issue by shamimbinnur** [open-sauced/landing-page#26]
### Describe the bug

On mobile view, the feature title looks huge and it loses the alignment
![02](https://user-images.githubusercontent.com/48399373/170848673-147902b5-e138-45bc-877e-01346cfe4151.PNG)

### Steps to reproduce

We can set the text size to about 24 pixels for the mobile view,
![01](https://user-images.githubusercontent.com/48399373/170848682-cc313a4e-51f4-4a42-a75b-67784ebcf0f6.PNG)

### Affected services

opensauced.pizza

### Platforms

Mobile

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
@bdougie what do you think about it?

**Comment by bdougie** [comment]
that looks great. Feel free to ship the update.

**Comment by shamimbinnur** [comment]
Solved the issue on c0c4a40a4d7d742b402f2c06f7fcdc30f74c591d
