### ISSUE TITLE
Two subscribe forms on mobile landing page

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#270]
![image](https://github.com/open-sauced/landing-page/assets/5713670/245f3437-8447-4f63-a6ca-7e4432db43fa)

**Comment by nickytonline** [comment]
It happens on larger screens too. Removing this line fixes it, so maybe the conditional check isn't quite right.

https://github.com/open-sauced/landing-page/blob/bd0fdfca7e74f71353a9e79feecd76077e326956/components/common/layout/PageLayout.tsx#L49

**Comment by Asin-Junior-Honore** [comment]
@nickytonline  I would love to fix this please🧑‍💻

**Comment by nickytonline** [comment]
@Asin-Junior-Honore, you're welcome to work on it. I'm just not positive if the line I mentioned should show the subscribe component in certain pages, or if it's included, does it double the subscribe form everywhere.

Deferring to @BekahHW or @chhristopher to see where the standalone subscribe form  should be or can we just remove the line I mentioned completely?

**Comment by Asin-Junior-Honore** [comment]
Alright then I guess I would just wait for @BekahHW or @chhristopher to give a precise response

**Comment by bdougie** [comment]
We can just go with removing the line @Asin-Junior-Honore

**Comment by nickytonline** [comment]
I've assigned the issue to you @Asin-Junior-Honore. Thanks for tackling this!

**Comment by Asin-Junior-Honore** [comment]
Hey 👋
 @nickytonline , @bdougie I have just finish resolving the issue kindly review my pr thanks😊

**Comment by nickytonline** [comment]
> Hey 👋
> 
>  @nickytonline , @bdougie I have just finish resolving the issue kindly review my pr thanks😊

No need to ping us directly. The whole team gets GitHub notifications. 😎
