### ISSUE TITLE
Bug: use cases menu under 404 page

### ISSUE THREAD

**Issue by zeucapua** [open-sauced/landing-page#276]
### Describe the bug

When getting the `404` page, the 'Use Cases' menu buttons cannot be clicked
![image](https://github.com/open-sauced/landing-page/assets/20603494/727952d7-d2b9-44fe-bee7-faee6122ea30)

### Steps to reproduce

1. Go to any non-existent page
2. Open the 'Use Cases' menu
3. See that you cannot click any sub items

**Comment by bdougie** [comment]
This is a repeat occurence. My suggestion is removing the z-50 from the tailwind on the 404 page. 

Similar to https://github.com/open-sauced/landing-page/pull/266 and https://github.com/open-sauced/landing-page/pull/260

**Comment by BekahHW** [comment]
Looks like @bdougie's PR fixed this, so I'm going to go ahead and close it.
