### ISSUE TITLE
Replace mooseheads

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#278]
We have not updated the mooseheads in over a year. My suggestion 

QuestDB -> [Appwrite](https://appwrite.io/assets)
Swimm -> [type.ai](https://type.ai/)

Need to get logos and swap them for ones with slate

<img width="1179" alt="Screenshot 2024-05-16 at 9 24 15 PM" src="https://github.com/open-sauced/landing-page/assets/5713670/73b5f3fb-0be3-4ebc-ab9a-75426a78e75a">

**Comment by nickaldwin** [comment]
Hi @bdougie i'm interested to work on this issue .take

**Comment by nickaldwin** [comment]
Hi @bdougie, Good morning, good afternoon, and good evening! I hope you're doing well.
I've created a separate branch and updated the two SVGs in the public/logos directory. Now, I need to update the homepage to reflect these changes. However, I’m having a hard time finding the correct files to modify.

Could you please help me locate the right file or component to update the logos on the homepage?

**Comment by bdougie** [comment]
This is all managed by Sanity and only accessible by staff.

**Comment by isabensusan** [comment]
closing since logos have already been replaced!
<img width="1407" alt="image" src="https://github.com/open-sauced/landing-page/assets/27322879/c8714909-0387-469b-bdc0-217fe42143f9">
