### ISSUE TITLE
replace product hub badge with the new link

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#288]
There is a new link for product that we need to replace the old one with. 

## light

<a href="https://www.producthunt.com/posts/starsearch?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-starsearch" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=455549&theme=light" alt="StarSearch - Copilot&#0044;&#0032;but&#0032;for&#0032;git&#0032;history | Product Hunt" style="width: 250px; height: 54px;" width="250" height="54" /></a>

## dark

<a href="https://www.producthunt.com/posts/starsearch?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-starsearch" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=455549&theme=dark" alt="StarSearch - Copilot&#0044;&#0032;but&#0032;for&#0032;git&#0032;history | Product Hunt" style="width: 250px; height: 54px;" width="250" height="54" /></a>

**Comment by bdougie** [comment]
getting copilot to do this.

**Comment by jpmcb** [comment]
Closed by https://github.com/open-sauced/landing-page/pull/289
