### ISSUE TITLE
Feature: Link Twitter handles in the testimonial section

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#29]
### Type of feature

🍕 Feature

### Current behavior

When viewing testimonials, any @ mentioned uses are not linkable. 
![Screen Shot 2022-07-06 at 2 45 26 PM](https://user-images.githubusercontent.com/5713670/177649122-351207ce-dfb9-4670-913b-2c0709cbbde1.png)

### Suggested solution

Make them linkable through either a service or sanitizing through markdown. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
@bdougie Can I take it over?

**Comment by TAKANOME-DEV** [comment]
@bdougie I used some transformation to replace twitter handles into links :
```js
const regex = /(?<=@)\w+/g

  const transformParagraph = (paragraph: string) => {
    const words = paragraph.split(' ')
    const transformedWords = words.map((word) => {
      if (word.match(regex)) {
        return `<a href="https://twitter.com/${word.replace(
          '@',
          ''
        )}" target="_blank" rel="noopener noreferrer">${word}</a>`
      }
      return word
    })
    return transformedWords.join(' ')
  }
```
After that I tried to use some libraries like [markdown-it](https://github.com/markdown-it/markdown-it), [marked](https://github.com/markedjs/marked) and others but they transform the string to `html` or `markdown` and it showed up as a string in the browser, so I passed the `transformParagraph` to the `p` tag through `dangerouslySetInnerHTML` attribute and here is the result:

![opensauced-landing](https://user-images.githubusercontent.com/79809121/190008957-b8377f33-98d6-409d-8c5f-139009516187.png)

What are your thoughts about it?

**Comment by SimranjitKaurMaan** [comment]
@TAKANOME-DEV Another possible solution could be to show the string content in p tag and show the twitter handle in a tag.  This can be done by parsing the entire testimonial content recursively and parse the string content and twitter handle separately. Parse the @content as a tag whereas parse without @ as p tag. Am i clear enough to explain the approach?

**Comment by TAKANOME-DEV** [comment]
Sorry, I'm not sure I understand what you mean.
How about taking this over and open a pr?

**Comment by SimranjitKaurMaan** [comment]
No worries. Let me open a PR for it. 

.take

**Comment by wasimapinjari** [comment]
.take

**Comment by wasimapinjari** [comment]
I fixed it!

![Screenshot (206)](https://github.com/open-sauced/landing-page/assets/95426296/2a7cf662-9256-4ae8-b956-71d568d49607)

**Comment by wasimapinjari** [comment]
But before that, when I forked the repo and clicked on this file there was an issue already (this is not related to my code):

This is how I set up the project:

```
npm i
npm run dev
```

After seeing the error I did the following:

```
npm run lint
npm ci
npm run dev
```

But the error remains:

![Screenshot (203)](https://github.com/open-sauced/landing-page/assets/95426296/0c0ff10c-f50c-41da-bbf9-a4affebd6ca7)

**Comment by a0m0rajab** [comment]
Thank you for your work! @wasimapinjari can you open a PR to check it from there? 
Plus, you have a great solution! when I first looked at this I thought about RegEx but your solution is simpler.

**Comment by wasimapinjari** [comment]
@a0m0rajab do you mind fixing this?

![Screenshot (223)](https://github.com/open-sauced/landing-page/assets/95426296/5c2c13b8-0697-4281-8068-489739d38600)

**Comment by a0m0rajab** [comment]
I do not think that this problem would prevent you from opening your PR, but to fix it you can do the next: 
take out the 

```js
const transition = { duration: 0.5, delay: 0.2, ease: 'easeInOut', type: 'spring', stiffness: 50 };
  return (
    <motion.div
      ref={refCard}
      initial={{ opacity: 0, y: cardInView ? 100 : 0 }}
      animate={{ opacity: cardInView ? 1 : 0 , y: cardInView ? 0 : 100 }}
      transition={transition}
      >
```

or use `as` from TS: 

```js
transition={{ duration: 0.5, delay: 0.2, ease: 'easeInOut', type: 'spring', stiffness: 50} as Transition}
```

**Comment by wasimapinjari** [comment]
@a0m0rajab Thanks, this will surely help me in the future if I encounter this type of error next time. 😀

**Comment by a0m0rajab** [comment]
You are welcome! it's great to see your contributions!
