### ISSUE TITLE
feat: Add app.opensauced.pizza to about page

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/landing-page#295]
Currently, we have three links on the about page but no path to app. I propose we remove hot and replace with app.

<img width="865" alt="image" src="https://github.com/open-sauced/landing-page/assets/34313413/fc7bc338-fdf0-4d0f-a01b-d0eda5c0a451">

https://opensauced.pizza/about

**Comment by bdougie** [comment]
Let's remove hot
