### ISSUE TITLE
Bug: broken links in the changelog page

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/landing-page#296]
### Describe the bug

broken links in the changelog page

![image](https://github.com/open-sauced/landing-page/assets/18273833/0e536e51-7a25-42bb-ab39-d6d277b2d5bb)

### Steps to reproduce

1. go to: https://opensauced.pizza/changelog/starsearch-is-live
2. try to click on the oss.fyi/ph 
3. it will direct you to relative link instead of absolute one.

**Comment by BekahHW** [comment]
Thanks @a0m0rajab! It should work now.
