### ISSUE TITLE
Add better filtering for adding a GH org to changelog

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/landing-page#332]
We've made some great upgrades to the UX for adding a GH org that are worth sharing.

ref: https://github.com/open-sauced/app/pull/3665

Related: @isabensusan is working on the image

## Process

The changelog is done in Sanity. 

1. Login to OpenSauced Sanity
2. Open Sanity Studio
3. Select Changelog base
4. Create a new Changelog entry
5. In the Changelog Content input, copy and paste the image from Isa first. Add your write up for the following.

**Comment by brandonroberts** [comment]
Changelog entry has been added https://opensauced.sanity.studio/desk/changelog;4f1c1962-e26b-4baf-bf6c-5bdfdc2dc350
