### ISSUE TITLE
Feature: improve quality of images rendered on the blog

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/landing-page#339]
### Suggested solution

Currently, when images are rendered on the blog, they're low quality and small. There also are no controls for how to format them. Right now they're mostly left aligned, and it looks off. At the very least, they should be centered. 

We should try to improve the image quality and styling.

**Comment by zeucapua** [comment]
Closing issue, this can be fixed via the Sanity CMS by removing the 'w=450' from the image URLs pasted on the markdown per blog.
