### ISSUE TITLE
Bug: Changelog Entries aren't clickable on mobile

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/landing-page#344]
### Describe the bug

When you're on the changelog page you can't click the title of a post to go to the individual changelog page.

This is happening in Safari and chrome in ios. It's worth noting that clicking the "See more..." isn't the same thing as going to the individual page, as that cuts off the entries.

### Steps to reproduce

1. Go to https://opensauced.pizza/changelog on mobile
2. Try to click a title. For example:

![image](https://github.com/user-attachments/assets/56e1ab74-4af0-401a-a716-6f544e3241bc)
3. Nothing happens

**Comment by nickytonline** [comment]
It looks like on mobile the titles get rendered as text and not links.

**Comment by dev-phantom** [comment]
yea
adding this 
` <Link
              href={`/changelog/${slug?.current}`}
              className="hover:text-brandOrange hover:decoration-brandOrange transition-all"
            >
              {title}
            </Link>`
  
  here https://github.com/open-sauced/landing-page/blob/7dfaa7d6c02a5424644fe88355a50b0b6de08fc3/components/sections/changelog/Changelog.tsx#L90
  fixes the issue

**Comment by dev-phantom** [comment]
.take 

pushing this immediatly my PR gets merged
