### ISSUE TITLE
Bug: Latest Changelog throwing a 500 when clicked

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/landing-page#345]
### Describe the bug

When you click the SBOM changelog post at the top of the [changelog page](https://opensauced.pizza/changelog), you get a 500 error.

### Steps to reproduce

1. Go to https://opensauced.pizza/changelog
2. Click the SBOM page

**Comment by nickytonline** [comment]
If you run it locally in dev mode, this is the error surfaced.

![CleanShot 2024-08-26 at 12 25 09](https://github.com/user-attachments/assets/ad310125-c3b1-4207-ae4a-a9a7b255e4ac)
