### ISSUE TITLE
Feature: OpenSauced CLI landing page

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/landing-page#346]
### Suggested solution

In an effort to re-vitalize the CLI, we should have a `opensauced.pizza/cli` landing page similar to other install sites. For example, here's GitHub's CLI landing page:

![Screenshot 2024-08-27 at 3 05 26 PM](https://github.com/user-attachments/assets/0ee964ac-789f-447d-a594-7ae1b7fa1cf8)

And here's Homebrew's install landing page:

![Screenshot 2024-08-27 at 3 06 07 PM](https://github.com/user-attachments/assets/ac3822cc-6ecc-47e4-8712-d5c68cf98996)

---

Requirements:

- Include simple brew installation instructions: `brew install open-sauced/tap/pizza` and "download" link to latest GitHub release (like the GitHub landing page does)
- Some copy on what the CLI is and or quickstart on using it.

Bonus:
- A screen-capture of the CLI in use

**Comment by nickytonline** [comment]
+1 to this. I really like the GH CLI's page.

**Comment by BekahHW** [comment]
How's this for copy:

# Boost your workflow with our pizza CLI

Generate CODEOWNERS, identify experts, and gain project insights – all from your terminal. Open-source, free, and ready to supercharge your development process.

```
brew install pizza
```
## What the pizza cli can do:

📄 CODEOWNERS file generation
👩‍💻 Expert developer identification
🚀 Streamlined onboarding
🏛️ Legacy code management
🤝 Cross-team collaboration tools

## Improve Your Development Process

**OpenSauced pizza CLI**: Providing the tools you need to optimize code ownership and team collaboration.

[`pizza-cli` repository →](https://github.com/open-sauced/pizza-cli)
[Learn more in our docs →](https://opensauced.pizza/docs/tools/pizza-cli/)

**Comment by zeucapua** [comment]
Reminder for me: use https://github.com/charmbracelet/vhs for CLI demos, https://github.com/charmbracelet/freeze for CLI screenshots
