### ISSUE TITLE
Bug: Time icon not lined up properly with text and other icons on blog post pages

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/landing-page#348]
The time icon not lined up properly with text and other icons on blog post pages.

![CleanShot 2024-09-03 at 15 46 55](https://github.com/user-attachments/assets/80e90eae-10ad-40f2-9aba-e63d6d8d0446)

**Comment by dev-phantom** [comment]
![image](https://github.com/user-attachments/assets/d6d350d9-5679-436a-a99c-f955851f59c2)
can you try refreshing maybe it's network 
or add steps to reproduce

**Comment by nickytonline** [comment]
It happens in Chromium based browsers, Safari, and Firefox all on macOS. Not sure if it's an issue on Windows.

![CleanShot 2024-09-07 at 17 07 39](https://github.com/user-attachments/assets/98b29143-6dd2-4e41-90f4-f94ac84f7bf0)

**Comment by dev-phantom** [comment]
oh yea seen

**Comment by dev-phantom** [comment]
adding items-center here should fix this 
https://github.com/open-sauced/landing-page/blob/7dfaa7d6c02a5424644fe88355a50b0b6de08fc3/components/sections/blog/%5Bslug%5D/PageContent.tsx#L62

.take
