### ISSUE TITLE
Bug: Featured blog is not editable in Sanity Studio

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#43]
### Describe the bug

When attempting to edit the featured blog links, I do not see any posts. 

<img width="1840" alt="Screen Shot 2022-09-20 at 4 34 19 AM" src="https://user-images.githubusercontent.com/5713670/191247700-3bb8ad86-26c9-4d34-8648-3876aa96e492.png">

### Steps to reproduce

1. Navigate to https://opensauced.sanity.studio/desk/featuredBlog
2. Note the empty section

### Affected services

opensauced.pizza

### Additional context

https://opensauced.sanity.studio/desk/featuredBlog

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
@bdougie Because of changing the "saucy blog" to "featured blog" the previous data you have saved is lost now. We still see the features blogs probably for the caching. We will be needed to add the feature blog  again from the dashboard.

**Comment by bdougie** [comment]
That's ok, I will recreate it.
