### ISSUE TITLE
Feature: Add Layout component to the project

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/landing-page#49]
### Type of feature

🍕 Feature

### Current behavior

Current we have duplicate `head` tags for site meta across all pages which doesn't look nice as far as clean code matters

### Suggested solution

We could create a `Layout` or `Seo` container to wrap every page component that has metadata in it.

### Suggested Approach

 Create a `Layout `or `Seo `component that accepts props of:

- `children` - the child component
- `customMeta`  the metadata for SEO
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
@SunGoldTech  I think the "SEO component" would be the best way as the SEO data are coming from the backend, and those data are different for different pages!

**Comment by dev-phantom** [comment]
.take
