### ISSUE TITLE
Feature: Add links to the testimonials

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#5]
### Type of feature

🍕 Feature

### Current behavior

The testimonials are meant to be links to the original tweets. 

![Screen Shot 2022-05-10 at 12 50 39 PM](https://user-images.githubusercontent.com/5713670/167710641-83a1d023-8768-4c15-a118-dcc3b3f84dde.png)

### Suggested solution

Provide url input in the sanity data 

1. Let's make the username clickable that opens tab to the tweet. 

2. We can also remove the date from the displayed data.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
This issue has been fixed on the commit 4d09f7bcea5fde924a990a963c406b765d68abec
