### ISSUE TITLE
Bug: Featured blogs are not rendering. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#50]
### Describe the bug

#39 the item saucyBlog was replaced with featuredBlogs, but the site is still rendering the old saucyBlog post. 

<img width="1552" alt="Screen Shot 2022-09-29 at 7 47 01 AM" src="https://user-images.githubusercontent.com/5713670/193064399-dbb53fb6-cc0c-44a4-b4a6-7e6c6286bf1e.png">

### Steps to reproduce

@shamimbinnur can you confirm if this is connect correctly. 

### Affected services

opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
@bdougie There was a tiny bug, but now this is resolved here  #51
