### ISSUE TITLE
Bug: Blog needs to be a local link "/blog"

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#53]
### Describe the bug

The way the navigation is setup in the CMS, it enforces external links only. Need to add an option to remove the target="_blank"

### Steps to reproduce

1. Click the blog link
2. It should not open a new tab.

### Affected services

opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
@bdougie

If you mark a blog "as native" it will not be required to enter an external URL, and if you click on the link it will take you to "/blog/slug"

If don't mark it as native you will be required to enter the URL of the post, and when you will click on the post it will redirect you to that URL. No new tab will be opened.

Did I make it clear or you meant something else?

**Comment by bdougie** [comment]
https://user-images.githubusercontent.com/5713670/193716635-fad9ca04-ce44-480b-9591-1ae3fb54bc03.mov

I am referring to the blog link in the nav. 

<img width="724" alt="Screen Shot 2022-10-03 at 6 45 21 PM" src="https://user-images.githubusercontent.com/5713670/193716758-77d413b2-48d6-4b67-bc5f-196e61ccbf70.png">
