### ISSUE TITLE
Feature: Testimonial title needs to be updates

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#6]
### Type of feature

🍕 Feature

### Current behavior

Title of the testimonials is lorem ipsum. 

### Suggested solution

Let's change the title to "The value of open source." for now. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
This issue has been fixed on commit 014c50bfe3b8348dff937b3a06acb3b14791c1e5
