### ISSUE TITLE
Feature: Details feature pages needs back button

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#7]
### Type of feature

🍕 Feature

### Current behavior

At the moment when visiting the details pages, there is no nav. 

![Screen Shot 2022-05-10 at 12 52 55 PM](https://user-images.githubusercontent.com/5713670/167711100-f13d4a04-7705-4353-8d9e-05ffcb0aa5ac.png)

### Suggested solution

Can we include a back button/arrow 

![Screen Shot 2022-05-11 at 6 58 45 AM](https://user-images.githubusercontent.com/5713670/167868068-023449e0-20cb-4bc8-adee-ca4e95fe356f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
This issue has been fixed on commit 9a088b01ab3bb878391d784e3a34833ece7cb2ac
