### ISSUE TITLE
Production Bug: Rendering issue in hero? "Unlock the power of $yellow-to-orangeOpen Source$yellow-to-orange"

### ISSUE THREAD

**Issue by davidnagli** [open-sauced/landing-page#74]
### Describe the bug

Sorry if this was an intentional design thing and I'm just being stupid, but I figured I'd report it just in case. The giant heading on the landing page says: 

>  Unlock the power of$yellow-to-orangeOpen Source$yellow-to-orange

I've been trying to figure out if this was an intentional design to trigger open-source devs into being interested, or if it was actually supposed to be the class name or some other internal mechanism for controlling the text gradient but instead got displayed as text by accident.

I can create a PR to try to fix it if that's something that needs to be fixed :)

### Steps to reproduce

Open [https://opensauced.pizza/](https://opensauced.pizza/)

<img width="943" alt="image" src="https://user-images.githubusercontent.com/6759650/205965862-15c97be1-f5b7-4593-903d-446f901c65ba.png">

### Affected services

opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by stefanvucic** [comment]
Hello, @davidnagli as I can see this issue is resolved?

**Comment by Tickerabucky2** [comment]
Hello, @davidnagli as I can see this issue is resolved?
