### ISSUE TITLE
Feature: Dynamic pricing labels 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#83]
### Type of feature

🍕 Feature

### Current behavior

<img width="1330" alt="Screen Shot 2022-12-12 at 1 32 19 PM" src="https://user-images.githubusercontent.com/5713670/207159106-d4847933-c053-4b74-8d62-ec71b11aec37.png">

### Suggested solution

Buttons need different CTA

Limited Acces - Get Started
Full Access - Get Started
Enterprise -  Contact Us

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by Tickerabucky2** [comment]
Hello @bdougie, this issue has been resolved in the PR [#85](https://github.com/open-sauced/landing-page/pull/85)
