### ISSUE TITLE
Bug: Blue border seems off

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#86]
### Describe the bug

reported [here](https://twitter.com/mynameissalah/status/1602708937584820225?s=20&t=W9XOlKfBuEa_kNmIliSNng) 

![IMG_4977](https://user-images.githubusercontent.com/5713670/207408244-642b8062-bf1d-4313-b46e-a6504dd8d32f.PNG)

### Steps to reproduce

On mobile, open the menu.

I'd suggest using grey there.

### Affected services

opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
I saw the border only the first time I opened the menu, after that it's no longer visible. Did you noticed the same thing?
We can also get rid of it (`display: none`) if it's not needed

**Comment by dev-phantom** [comment]
please has this issue been fixed?

**Comment by SimranjitKaurMaan** [comment]
I tried to reproduce this issue. This issue seems to be no longer reproducible in my mobile. can we close this issue?
![Screenshot_2023-01-14-10-53-31-53_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/9392954/212457412-576002b0-f1a5-4e79-9e53-eddb63ce8fd4.jpg)

**Comment by TAKANOME-DEV** [comment]
I still can see it though :pizza:

**Comment by SimranjitKaurMaan** [comment]
> I still can see it though 🍕

@TAKANOME-DEV in which device are you seeing this?

**Comment by TAKANOME-DEV** [comment]
I'm on iPhone 6s Plus :iphone:

**Comment by dev-phantom** [comment]
this issue has been fixed
kindly close this issue
