### ISSUE TITLE
Feature: New color scheme. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#9]
### Type of feature

🍕 Feature

### Current behavior

![Screen Shot 2022-05-11 at 7 01 11 AM](https://user-images.githubusercontent.com/5713670/167868328-391097e3-593b-4f5b-bbe4-f652e3832093.png)

### Suggested solution

![Screen Shot 2022-05-11 at 7 01 25 AM](https://user-images.githubusercontent.com/5713670/167868356-d174844d-e8f2-4fdf-a804-68fe72427c51.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
Color scheme has been updated on commit d0b699d17823ed11058a5d0c2607d4d97a4d7378
