### ISSUE TITLE
Bug: Weird margins on the socials in Footer on landscape mode.

### ISSUE THREAD

**Issue by HoldUpFjord** [open-sauced/landing-page#91]
### Describe the bug

On certain mobile devices/layouts the socials are missing margins on the right: 

![OpenSauced footer bug](https://user-images.githubusercontent.com/93451889/210851091-65645b32-96f4-4609-ae48-ed1cc494b1bf.png)

### Steps to reproduce

1.) Go to developer tools
2.) Select mobile view
3.) Select "IPhone 12/13" on the devices drop-down menu.
4.) Switch to landscape mode
5.) Scroll down to Footer section.

At the top are my dev-tool settings as displayed in Firefox:
![OpenSauced footer bug settings](https://user-images.githubusercontent.com/93451889/210858654-214c3a8f-491a-4506-a7b9-39dbab566392.png)

I was able to replicate the issue in Google Chrome as well.

### Affected services

opensauced.pizza

### Platforms

Mobile

### Browsers

Chrome, Firefox

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by HoldUpFjord** [comment]
Hi,  
This is my first issue report, sorry if I mislabeled anything! If this is a noteworthy I'd definitely like to take it on and try to fix it. My initial thought is using media queries to specify the dimensions that are causing the issue and just adding a bit of margin on the right side. 

If there is a better way to approach that stays in-line with the codebase standards please let me know! I'd love to contribute.

**Comment by dev-phantom** [comment]
@bdougie can i take this

**Comment by bdougie** [comment]
Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by bdougie** [comment]
Please go for it. Just needs to be responsive and can be accomplished with the tailwind classes.

**Comment by dev-phantom** [comment]
ok sir

**Comment by bdougie** [comment]
Apologies @dev-phantom, we probably should have suggested a solution. I'd expect this to wrap the icons by adding a second row of icons. 

Let me know if you have thoughts on a solution @HoldUpFjord

**Comment by dev-phantom** [comment]
oh okay sir

**Comment by HoldUpFjord** [comment]
Ah I need to self assign in the future! That's my mistake.

**Comment by HoldUpFjord** [comment]
I think your solution is a good one @bdougie! Are you imagining using "flex-flow" to drop down icons one-by-one? Or are you imaging a breakpoint where half the icons move down to the second row to keep a visual symmetry?
 
If it's the former it seems like adding the tailwind class flex-wrap: https://tailwindcss.com/docs/flex-wrap to the div holding the icons provides a fix as seen here:

![openSauceBugFix](https://user-images.githubusercontent.com/93451889/210951477-b5c2dd6e-8cc7-4d38-9aa6-a6c0555dec9f.gif)


It's hard for me to say exactly where that class needs to be changed as I'm still getting acquainted with the codebase. It seems like I might need to be added to the Sanity CMS? I'll keep poking around and try to find the exact line that needs to be changed!

**Comment by HoldUpFjord** [comment]
Without being able to run it, I think it's line 50 in: components\common\SocialLinks.tsx that needs the "Flex-flow" class in the above solution!

**Comment by NsdHSO** [comment]
Hi @HoldUpFjord, another possible solution is [here](https://github.com/open-sauced/landing-page/blob/main/components/sections/Footer.tsx#L52) to apply `flex-shrink-0`

**Comment by HoldUpFjord** [comment]
Hey @NsdHSO! 

I believe @bdougie mentioned wanting a solution that wraps the icons. I was just able to get the page running locally and confirmed the flex-wrap works. It looks @dev-phantom already updated the change, so we should be good!
