### ISSUE TITLE
Feature: Update Read.me to mention that you need a .env file to run project locally.

### ISSUE THREAD

**Issue by HoldUpFjord** [open-sauced/landing-page#93]
### Type of feature

📝 Documentation

### Current behavior

Read.me omits stating that users need to add a .env file to root, as well as adding the Sanity_Project_Id to that file, for running locally. Could be improved to ease on-boarding in the future. 

![documentationOpenSauceEx1](https://user-images.githubusercontent.com/93451889/212410230-f49fd7c5-262b-49c8-ae07-55c83826ba9d.png)
&
![documentationOpenSauceEx2](https://user-images.githubusercontent.com/93451889/212410211-27879fec-621c-4114-a65c-07c148d42e26.png)

### Suggested solution

Adding a short piece of documentation to the 'Getting Started' section, or the 'SanityCMS' section, describing where to make the .env file, and how to format the Sanity_Project_ID string.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by HoldUpFjord** [comment]
I'd like this issue!

**Comment by TAKANOME-DEV** [comment]
Thanks for opening this issue. Since it's related to Sanity, I would suggest adding it into `CMS SANITY commands` section unless there are other environment variables to add to the `.env` file

**Comment by HoldUpFjord** [comment]
Thanks @TAKANOME-DEV, I'll start working on this now. I had a wedding I've been out of town for since Friday. 

I think that suggestion makes a lot of sense. I'll draft up a short piece of documentation to go in that section.

**Comment by bdougie** [comment]
I ended up just adding the sanity id back so the env is not needed. Sanity already manages the roles and access. So there is not risk in having it there. https://github.com/open-sauced/landing-page/issues/97
